import { Book } from './types';

export const INITIAL_BOOKS: Book[] = [
  {
    id: '1',
    author: 'Ali Eltari',
    title: 'Kështjella beszana',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/1/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '2',
    author: 'Agim Bajrami',
    title: 'Ndodhitë e Xhulios dhe miqve të tij',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/2/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '3',
    author: 'Agim Gjakova',
    title: 'Nën hijen ë pavdekësisë',
    stock: 12,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/3/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '4',
    author: 'Aleksandër Moisiu',
    title: 'Vepra letrare',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/4/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '5',
    author: 'Ali Asllani',
    title: 'Vidi-Vidi pëllumbeshë',
    stock: 5,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/5/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '6',
    author: 'Ali Eltari',
    title: 'Kudhra e argjendtë',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/6/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '7',
    author: 'Anastas Kondo',
    title: 'Partizani vogël velo',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/7/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '8',
    author: 'Andon Zako Cajupi',
    title: 'Poezia shqipe',
    stock: 4,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/8/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '9',
    author: 'Andon Zako Cajupi',
    title: 'Baba Tomorri',
    stock: 11,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/9/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '10',
    author: 'Andon Zako Cajupi',
    title: '14 vjeç dhëndër',
    stock: 24,
    genre: 'Dramë',
    coverUrl: 'https://picsum.photos/seed/10/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '11',
    author: 'Anton Papleka',
    title: 'Rrëmbimi I Tanushës',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/11/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '12',
    author: 'Anton Papleka',
    title: 'Legjenda e tregime të moçme shqiptare',
    stock: 1,
    genre: 'Legjenda',
    coverUrl: 'https://picsum.photos/seed/12/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '13',
    author: 'Anton Papleka',
    title: 'Vdekja e lisnajës',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/13/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '14',
    author: 'Aqif Malaj',
    title: 'Pasqyra e mrekullive',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/14/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '15',
    author: 'Aqif Malaj',
    title: 'Ne arbërit',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/15/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '16',
    author: 'Aqif Malaj',
    title: 'Unaza e mbretëreshës',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/16/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '17',
    author: 'Arian Leka',
    title: 'Legjendat më të bukura',
    stock: 3,
    genre: 'Legjenda',
    coverUrl: 'https://picsum.photos/seed/17/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '18',
    author: 'Arsen J. Mustaqi dhe Mehmet T. Gëzhilli',
    title: 'Gjëegjëza',
    stock: 3,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/18/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '19',
    author: 'Asdreni',
    title: 'Poezi të zgjedhura',
    stock: 6,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/19/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '20',
    author: 'Asdreni',
    title: 'Vlera e atdheut',
    stock: 6,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/20/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '21',
    author: 'Asdreni',
    title: 'Lulëkuqja',
    stock: 9,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/21/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '22',
    author: 'Babai i Shpendit',
    title: 'Krahët e shpendit (poezi)',
    stock: 3,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/22/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '23',
    author: 'Besnik Alibali',
    title: 'Misionari I ringjalljes',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/23/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '24',
    author: 'Bledar Kurti',
    title: 'Man Ray dhe surealizmi',
    stock: 1,
    genre: 'Art',
    coverUrl: 'https://picsum.photos/seed/24/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '25',
    author: 'Bledar Kurti',
    title: 'Udhëtimi në gjurmet e vjetra dhe të reja të qytetërimit',
    stock: 1,
    genre: 'Histori',
    coverUrl: 'https://picsum.photos/seed/25/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '26',
    author: 'Blegina Kananaj Bala',
    title: 'Flutur në shpirtin tim',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/26/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '27',
    author: 'Wngjëll Zotaj',
    title: 'E vogëla sa një ftua (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/27/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '28',
    author: 'Ernest Koliqi',
    title: 'Tregtar flamujsh',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/28/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '29',
    author: 'Faik Konica',
    title: 'Pejsazh',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/29/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '30',
    author: 'Fatos Arapi',
    title: 'Deti në mes',
    stock: 7,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/30/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '31',
    author: 'Ferit Lamaj',
    title: 'Dhelpra e trojës',
    stock: 3,
    genre: 'Fabul',
    coverUrl: 'https://picsum.photos/seed/31/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '32',
    author: 'Floresha Dado',
    title: 'Andon Zako Cajupi (jeta dhe veprat)',
    stock: 2,
    genre: 'Biografi',
    coverUrl: 'https://picsum.photos/seed/32/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '33',
    author: 'Foto Malo',
    title: 'Nga Lapraka në Alaskë',
    stock: 2,
    genre: 'Udhëpërshkrim',
    coverUrl: 'https://picsum.photos/seed/33/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '34',
    author: 'Frederik Rreshpja',
    title: 'Lirika të zgjedhura',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/34/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '35',
    author: 'Frederik Shuraja',
    title: 'Legjendat më të bukura',
    stock: 1,
    genre: 'Legjenda',
    coverUrl: 'https://picsum.photos/seed/35/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '36',
    author: 'Gavril Dara I riu',
    title: 'Kënga e sprasme e balës',
    stock: 11,
    genre: 'Epos',
    coverUrl: 'https://picsum.photos/seed/36/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '37',
    author: 'Gjergj Fishta',
    title: 'Jeta dhe veprat',
    stock: 1,
    genre: 'Biografi',
    coverUrl: 'https://picsum.photos/seed/37/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '38',
    author: 'Gjergj Fishta',
    title: 'Mrizi I zanave',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/38/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '39',
    author: 'Gjergj Fishta',
    title: 'Lahuta e Malësisë',
    stock: 4,
    genre: 'Epos',
    coverUrl: 'https://picsum.photos/seed/39/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '40',
    author: 'Hajro Ulqinaku',
    title: 'Libri për detin',
    stock: 5,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/40/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '41',
    author: 'Halit Shamata',
    title: 'Dyer të paputhitura',
    stock: 4,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/41/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '42',
    author: 'Hamdi Meça',
    title: 'Nëna me zemër sa liria',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/42/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '43',
    author: 'Hysen Kobellari',
    title: 'Rrobaqepëse Xhiljeta',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/43/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '44',
    author: 'Kostandin Gjika',
    title: 'Loti I Diellit',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/44/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '45',
    author: 'Lasgush Poradeci',
    title: 'Lirika',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/45/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '46',
    author: 'Merita Thartori',
    title: 'Shtrati I dytë (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/46/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '47',
    author: 'Muharrem Gazioni',
    title: 'Dhe pylli zbriti mbi krahë zogjsh',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/47/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '48',
    author: 'Myzejen Konduri',
    title: 'Shtegu I kujtesës',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/48/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '49',
    author: 'Myzejen Konduri',
    title: 'Zëri i heshtjes',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/49/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '50',
    author: 'Myzejen Konduri',
    title: 'Lot I këputur',
    stock: 5,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/50/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '51',
    author: 'Natasha Arbana',
    title: 'Të fshehur pas ajrit',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/51/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '52',
    author: 'Nikolla Spathari',
    title: 'Djemtë e dikurshëm',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/52/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '53',
    author: 'Nikolla Spathari',
    title: 'Përkohësisht e bukur (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/53/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '54',
    author: 'Oti Keçi',
    title: 'Sytë e një femre(poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/54/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '55',
    author: 'Pol Milo',
    title: 'Shtegtimi I dinozaurëve fluturues',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/55/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '56',
    author: 'Ruzhdi Gole',
    title: 'Pak terr dhe etje',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/56/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '57',
    author: 'Sabit Idrizi',
    title: 'Përderisa është e martë (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/57/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '58',
    author: 'Skifter Këlliçi',
    title: 'Tirani ngrihet nga varri',
    stock: 4,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/58/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '59',
    author: 'Sokol Lakova',
    title: 'Shokë të pandarë',
    stock: 24,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/59/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '60',
    author: 'Trandafile Molla (Baja)',
    title: 'Më thërret një zë',
    stock: 4,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/60/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '61',
    author: 'Trandafile Molla (Baja)',
    title: 'Dallëndyshe në fluturim',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/61/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '62',
    author: 'Uran Butka',
    title: 'Vdekja e bardhë',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/62/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '63',
    author: 'Visar Zhiti',
    title: 'Thesaret e frikës',
    stock: 6,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/63/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '64',
    author: 'Ymer Nurkja',
    title: 'Peng midis ekuinoksesh',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/64/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '65',
    author: 'Ymer Nurkja',
    title: 'Zëra në xhungël',
    stock: 8,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/65/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '66',
    author: 'Zef Serembe',
    title: 'Vjersha',
    stock: 6,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/66/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '67',
    author: 'Fatos Kongoli',
    title: 'I humburi',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/67/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '68',
    author: 'Edlira Qefalia',
    title: 'Rrëfime',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/68/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '69',
    author: 'Bashkim Hoxha',
    title: 'Një lolo de një mbret',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/69/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '70',
    author: 'Preç Zogaj',
    title: 'Qielli I gjithëkujt (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/70/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '71',
    author: 'Thanas Jorgji',
    title: 'Gjahtarë si ne',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/71/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '72',
    author: 'Bashkim Hoxha',
    title: 'Mbreti I vesës',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/72/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '73',
    author: 'Darien Levani',
    title: 'Njeriu unë (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/73/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '74',
    author: 'Dhimiter Xhuvani',
    title: 'Sytë e zotit',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/74/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '75',
    author: 'Shpëtim Myshketa',
    title: 'Fli dashuria ime (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/75/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '76',
    author: 'Vasil Kovi',
    title: 'Ji pak fëmijë (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/76/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '77',
    author: 'Ruzhdi Gole',
    title: 'Dihatje në livadhin e mbrëmjes (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/77/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '78',
    author: 'Minella Mano',
    title: 'Të rikujtoj (poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/78/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '79',
    author: 'Nazif Agalliu',
    title: 'Tre njerëz të një qyteti',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/79/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '80',
    author: 'Miço Kallamata',
    title: 'Asnjanësia e zotit Lulo',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/80/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '81',
    author: 'Fatmir Gega',
    title: 'Bukuria dhe mosha',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/81/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '82',
    author: 'Vilsoni dhe Genci',
    title: 'Jeta dhe veprat',
    stock: 4,
    genre: 'Biografi',
    coverUrl: 'https://picsum.photos/seed/82/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '83',
    author: 'Petro Marko',
    title: 'Shpella e piratëve',
    stock: 39,
    genre: 'Aventurë',
    coverUrl: 'https://picsum.photos/seed/83/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '84',
    author: 'Petro Marko',
    title: 'Retë dhe gurët',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/84/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '85',
    author: 'Petro Marko',
    title: 'Fantazma dhe plani (tre plus katër)',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/85/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '86',
    author: 'Petro Marko',
    title: 'Griva',
    stock: 7,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/86/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '87',
    author: 'Jeronim De Rada',
    title: 'Jeronim de rada',
    stock: 5,
    genre: 'Biografi',
    coverUrl: 'https://picsum.photos/seed/87/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '88',
    author: 'Petro Marko',
    title: 'Nata e ustikës',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/88/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '89',
    author: 'Jeronim De Rada',
    title: 'Këngët e Milosaos',
    stock: 5,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/89/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '90',
    author: 'Jeronim De Rada',
    title: 'Vepra letrare',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/90/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '91',
    author: 'Jeronim De Rada',
    title: 'Rrëfime të Arbërit',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/91/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '92',
    author: 'Aristofani',
    title: 'Paqja',
    stock: 2,
    genre: 'Dramë',
    coverUrl: 'https://picsum.photos/seed/92/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '93',
    author: 'Jeronim De Rada',
    title: 'Këngë të Milosaut',
    stock: 5,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/93/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '94',
    author: 'Xhevat Beqaraj',
    title: 'Rruazat e vesës',
    stock: 5,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/94/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '95',
    author: 'Kozeta Mamaqi',
    title: 'Loja me telefonin',
    stock: 3,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/95/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '96',
    author: 'Viktor Canosinaj',
    title: 'Katër yje në qytet',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/96/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '97',
    author: 'Viktor Canosinaj',
    title: 'Elegji e re për Van Gogun',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/97/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '98',
    author: 'Viktor Canosinaj',
    title: 'Në ndjekje të vampirëve',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/98/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '99',
    author: 'Viktor Canosinaj',
    title: 'P4',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/99/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '100',
    author: 'Viktor Canosinaj',
    title: 'Lulet e përgjakura të 7 marsit',
    stock: 9,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/100/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '101',
    author: 'Viktor Canosinaj',
    title: 'Ikja e pëllumbave',
    stock: 6,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/101/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '102',
    author: 'Viktor Canosinaj',
    title: 'Meri yll',
    stock: 4,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/102/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '103',
    author: 'Viktor Canosinaj',
    title: 'Në rrugë',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/103/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '104',
    author: 'Viktor Canosinaj',
    title: 'Gjenerali prej bore',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/104/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '105',
    author: 'Viktor Canosinaj',
    title: 'Biri I erës',
    stock: 15,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/105/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '106',
    author: 'Viktor Canosinaj',
    title: 'Foleja e madhe',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/106/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '107',
    author: 'Viktor Canosinaj',
    title: 'Monstrat e rrugës së mimozave',
    stock: 11,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/107/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '108',
    author: 'Viktor Canosinaj',
    title: 'Ata kërkonin lumturinë',
    stock: 17,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/108/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '109',
    author: 'Viktor Canosinaj',
    title: 'Lamtumirë guacka ime',
    stock: 8,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/109/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '110',
    author: 'Viktor Canosinaj',
    title: 'Zemra në pëllëmbë të dorës',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/110/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '111',
    author: 'Viktor Canosinaj',
    title: 'Lulemaji',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/111/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '112',
    author: 'Viktor Canosinaj',
    title: 'ëngjëjt nuk zbresin në tokë',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/112/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '113',
    author: 'Viktor Canosinaj',
    title: 'ëndrat e anijes me vela',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/113/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '114',
    author: 'Viktor Canosinaj',
    title: 'Princi diellor',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/114/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '115',
    author: 'Viktor Canosinaj',
    title: 'Djali që shikonte detin',
    stock: 4,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/115/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '116',
    author: 'Viktor Canosinaj',
    title: 'Bormal',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/116/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '117',
    author: 'Viktor Canosinaj',
    title: 'Përmbi dallgë e zjarre',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/117/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '118',
    author: 'Viktor Canosinaj',
    title: 'Aventurat në ishullin lundrues',
    stock: 15,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/118/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '119',
    author: 'Viktor Canosinaj',
    title: 'Piratja sybojëqielli',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/119/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '120',
    author: 'Visar Zhiti',
    title: 'Funerali I pafundë',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/120/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '121',
    author: 'Sulejman Xh.Kaba',
    title: 'Fluturim I pandërprerë',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/121/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '122',
    author: 'Sulejman Xh.Kaba',
    title: 'Hija e atij tjetrit',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/122/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '123',
    author: 'Zhak Pusti',
    title: 'Një plak I vitit të ri ndryshe nga të tjerët',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/123/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '124',
    author: 'Kolet Vivje',
    title: 'Autostop',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/124/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '125',
    author: 'Hil Mosi',
    title: 'Zani I atdheut',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/125/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '126',
    author: 'Koço Kosta',
    title: 'Buka e një stine me borë',
    stock: 6,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/126/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '127',
    author: 'Agim Dedej',
    title: 'Më udhëkryq të moshës',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/127/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '128',
    author: 'Naum Prifti',
    title: 'Ndjekësi I kuajve',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/128/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '129',
    author: 'Vladimir Ndini',
    title: 'Rrëfime nga cikli I kreshnikëve',
    stock: 1,
    genre: 'Epos',
    coverUrl: 'https://picsum.photos/seed/129/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '130',
    author: 'Nonda Bulka',
    title: 'Fabula në prozë',
    stock: 6,
    genre: 'Fabul',
    coverUrl: 'https://picsum.photos/seed/130/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '131',
    author: 'Nasho Jorgaqi',
    title: 'Një tufë gonxhe dhe gjemba',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/131/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '132',
    author: 'Shpendi Topollaj',
    title: 'Gjithë dashuritë e mija',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/132/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '133',
    author: 'Silvana Leka',
    title: 'Gushkuqi',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/133/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '134',
    author: 'Halit Shamata',
    title: 'Moshë pa kohë',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/134/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '135',
    author: 'Ylli Toska',
    title: 'Kur shkërmoqej diktatura',
    stock: 1,
    genre: 'Histori',
    coverUrl: 'https://picsum.photos/seed/135/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '136',
    author: 'Roland Gjoza',
    title: 'Romeo,Zhulieta dhe errësira',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/136/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '137',
    author: 'Shejh Jonuzi',
    title: 'Fjalë e valë (Revistë letrare)',
    stock: 1,
    genre: 'Revistë',
    coverUrl: 'https://picsum.photos/seed/137/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '138',
    author: 'Manushaqe Ramadan Shalsi',
    title: 'Grimcat e shpirtit rrinë zgjuar (Poezi)',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/138/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '139',
    author: 'Xhevahir Spahiu',
    title: 'Zogj të kaltër',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/139/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '140',
    author: 'Bashkim Çuçi',
    title: 'Pesë porosi të babagjyshit',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/140/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '141',
    author: 'Vladimir Ilia',
    title: 'Më fal',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/141/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '142',
    author: 'Zyra Ahmetaj',
    title: 'Fluturojnë ëngjëjt',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/142/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '143',
    author: 'Frederik Ndoci',
    title: 'I lindur dhe plak I divorcuar',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/143/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '144',
    author: 'Vladimir Shyti',
    title: 'Kush është fajtori???',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/144/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '145',
    author: 'Zef Serembe',
    title: 'Poezi',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/145/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '146',
    author: 'Niko Deda',
    title: 'Barinjtë e detit',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/146/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '147',
    author: 'Ndre Mjeda',
    title: 'Zambakët',
    stock: 5,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/147/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '148',
    author: 'Ndre Mjeda',
    title: 'Juvenilja',
    stock: 5,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/148/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '149',
    author: 'Ndre Mjeda',
    title: 'Dimri dhe plaku',
    stock: 7,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/149/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '150',
    author: 'Ndre Mjeda',
    title: 'Poezi',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/150/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '151',
    author: 'Mehmet Gëzhilli',
    title: 'Fan S.Noli',
    stock: 1,
    genre: 'Biografi',
    coverUrl: 'https://picsum.photos/seed/151/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '152',
    author: 'Fan S.Noli',
    title: 'Vepra 3',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/152/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '153',
    author: 'Fan S.Noli',
    title: 'Vepra 4',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/153/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '154',
    author: 'Fan S.Noli',
    title: 'Vepra 5',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/154/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '155',
    author: 'Fan S.Noli',
    title: 'Vjersha të zgjedhura',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/155/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '156',
    author: 'Fan S.Noli',
    title: 'Portrete dhe skica',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/156/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '157',
    author: 'Fan S.Noli',
    title: 'Magbethi(Ulliam Sheikspir)',
    stock: 1,
    genre: 'Dramë',
    coverUrl: 'https://picsum.photos/seed/157/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '158',
    author: 'Kajan Dinoshi',
    title: 'Poet në pleqëri',
    stock: 3,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/158/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '159',
    author: 'Virgjil Muçi',
    title: 'Përralla Shqiptare',
    stock: 2,
    genre: 'Përralla',
    coverUrl: 'https://picsum.photos/seed/159/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '160',
    author: 'Tomi Mato',
    title: 'Të vërteta të pathëna për Lasgushin',
    stock: 6,
    genre: 'Biografi',
    coverUrl: 'https://picsum.photos/seed/160/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '161',
    author: 'Gaqo Bushaka',
    title: 'Ariu artist',
    stock: 10,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/161/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '162',
    author: 'Gaqo Bushaka',
    title: 'Përralla',
    stock: 1,
    genre: 'Përralla',
    coverUrl: 'https://picsum.photos/seed/162/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '163',
    author: 'Gaqo Bushaka',
    title: 'Pushimet e Çufos',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/163/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '164',
    author: 'Gaqo Bushaka',
    title: 'Sokoli lexon vetë',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/164/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '165',
    author: 'Gaqo Bushaka',
    title: 'Xhamafshirësi I vogël',
    stock: 8,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/165/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '166',
    author: 'Gaqo Bushaka',
    title: 'Djaloshi nga Dyrrahu',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/166/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '167',
    author: 'Gaqo Bushaka',
    title: 'Çufoja dhe Bubi Kaçurrel',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/167/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '168',
    author: 'Gaqo Bushaka',
    title: 'Filmi I gjeneral Çufos',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/168/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '169',
    author: 'Gaqo Bushaka',
    title: 'Përrallat e shiut',
    stock: 1,
    genre: 'Përralla',
    coverUrl: 'https://picsum.photos/seed/169/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '170',
    author: 'Gaqo Bushaka',
    title: 'Legjendat e kalorësit të Skëndërbeut',
    stock: 5,
    genre: 'Legjenda',
    coverUrl: 'https://picsum.photos/seed/170/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '171',
    author: 'Gaqo Bushaka',
    title: 'Guna e zezë',
    stock: 8,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/171/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '172',
    author: 'Ramadan Pasmaçiu',
    title: 'Dashuria e nënës',
    stock: 12,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/172/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '173',
    author: 'Ramadan Pasmaçiu',
    title: 'Leka',
    stock: 7,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/173/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '174',
    author: 'Ramadan Pasmaçiu',
    title: 'Mësuesja',
    stock: 5,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/174/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '175',
    author: 'Ramadan Pasmaçiu',
    title: 'Udhëve të fëmijërisë',
    stock: 59,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/175/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '176',
    author: 'Ramadan Pasmaçiu',
    title: 'Vajza e vogël flokë verdhë',
    stock: 26,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/176/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '177',
    author: 'Ramadan Pasmaçiu',
    title: 'Xhufi 1',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/177/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '178',
    author: 'Ramadan Pasmaçiu',
    title: 'Xhufi 2',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/178/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '179',
    author: 'Ramadan Pasmaçiu',
    title: 'Shtjellat e Bardha',
    stock: 10,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/179/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '180',
    author: 'Ramadan Pasmaçiu',
    title: 'Nusja që kërkonte dyshek me pupla',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/180/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '181',
    author: 'Ramadan Pasmaçiu',
    title: 'Qerosi që çmendi Aganë',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/181/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '182',
    author: 'Ramadan Pasmaçiu',
    title: 'Gomari kur u bë kalë',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/182/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '183',
    author: 'Ramadan Pasmaçiu',
    title: 'Tri pëllëmbë shtat e shtatë pëllëmbë mjekër',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/183/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '184',
    author: 'Ramadan Pasmaçiu',
    title: 'Trimat dhe vashëza me emrin zanë',
    stock: 10,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/184/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '185',
    author: 'Ramadan Pasmaçiu',
    title: 'Dy shokët',
    stock: 14,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/185/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '186',
    author: 'Majn Rid',
    title: 'Të humburit në oqean',
    stock: 1,
    genre: 'Aventurë',
    coverUrl: 'https://picsum.photos/seed/186/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '187',
    author: 'Eida Milaqi',
    title: 'Trokas tek ju…',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/187/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '188',
    author: 'Arian Kadiu',
    title: 'Pas takimit me alienët',
    stock: 1,
    genre: 'Fanta-shkencë',
    coverUrl: 'https://picsum.photos/seed/188/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '189',
    author: 'Legjenda shqiptare',
    title: 'E bukura e liqenit',
    stock: 1,
    genre: 'Legjenda',
    coverUrl: 'https://picsum.photos/seed/189/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '190',
    author: 'Ferhat Çakërri',
    title: 'Ku ta gjej pranverën',
    stock: 4,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/190/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '191',
    author: 'Iliaz Bobaj',
    title: 'Dino Buzzati ndalohet në doganë',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/191/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '192',
    author: 'Zef Skiroi',
    title: 'Mili dhe Haidhea',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/192/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '193',
    author: 'Prokop Gjergjo',
    title: 'Jehonat e mesnatës',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/193/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '194',
    author: 'Resul Shabani',
    title: 'Dashuria e Kapitenit',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/194/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '195',
    author: 'Trumat Kapot',
    title: 'Qivuret e bëra me dorë',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/195/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '196',
    author: 'Ismail Kadare',
    title: 'Koha e shkrimeve',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/196/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '197',
    author: 'Ismail Kadare',
    title: 'Ftesë në studio',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/197/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '198',
    author: 'Ismail Kadare',
    title: 'Vepra 1',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/198/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '199',
    author: 'Ismail Kadare',
    title: 'Vepra 3',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/199/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '200',
    author: 'Ismail Kadare',
    title: 'Vepra 4',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/200/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '201',
    author: 'Ismail Kadare',
    title: 'Autobiografia e popullit në vargje',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/201/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '202',
    author: 'Ismail Kadare',
    title: 'Kështjella',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/202/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '203',
    author: 'Ismail Kadare',
    title: 'E penguara',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/203/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '204',
    author: 'Ismail Kadare',
    title: 'Prilli I thyer',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/204/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '205',
    author: 'Ismail Kadare',
    title: 'Kush e solli Doruntinën',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/205/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '206',
    author: 'Ismail Kadare',
    title: 'Princesha Argjiro',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/206/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '207',
    author: 'Ismail Kadare',
    title: 'Pasardhësit',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/207/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '208',
    author: 'Ismail Kadare',
    title: 'Koncert në fund të dimrit',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/208/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '209',
    author: 'Ismail Kadare',
    title: 'Ardhja e Migjenit në letërsinë shqipe',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/209/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '210',
    author: 'Ismail Kadare',
    title: 'Linjat e largëta',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/210/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '211',
    author: 'Mitrush Kuteli',
    title: 'Tregime të moçme shqiptare',
    stock: 5,
    genre: 'Legjenda',
    coverUrl: 'https://picsum.photos/seed/211/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '212',
    author: 'Mitrush Kuteli',
    title: 'Xinxifilua dhe prralla të tjera',
    stock: 2,
    genre: 'Përralla',
    coverUrl: 'https://picsum.photos/seed/212/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '213',
    author: 'Mitrush Kuteli',
    title: 'Tregime të zgjedhura',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/213/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '214',
    author: 'Nexhati Tafa',
    title: 'Qumështi I Rozafës',
    stock: 5,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/214/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '215',
    author: 'Naim Frashëri',
    title: 'Bagëti e bujqësia',
    stock: 5,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/215/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '216',
    author: 'Teodor Keko',
    title: 'Lajmëtarja e vdekjeve',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/216/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '217',
    author: 'Migjeni',
    title: 'Vargje të lira',
    stock: 1,
    genre: 'Poezi',
    coverUrl: 'https://picsum.photos/seed/217/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '218',
    author: 'Sami Frashëri',
    title: 'Dheu është flori',
    stock: 27,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/218/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '219',
    author: 'Sami Frashëri',
    title: 'Shqipëria çka qenë, çështë dhe çdo të bëhet',
    stock: 3,
    genre: 'Histori',
    coverUrl: 'https://picsum.photos/seed/219/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '220',
    author: 'Anton Pashku',
    title: 'Kulla',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/220/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '221',
    author: 'Gjergj Zheji',
    title: 'Muret e Krujës',
    stock: 4,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/221/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '222',
    author: 'Ndoc Papleka',
    title: 'Imiri prej Monunit',
    stock: 23,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/222/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '223',
    author: 'Petraq Zoto',
    title: 'Burimi I drerit',
    stock: 3,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/223/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '224',
    author: 'Viron Kona',
    title: 'Pyesni Bubulinon',
    stock: 2,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/224/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '225',
    author: 'Dritëro Agolli',
    title: 'Çudira dhe marrëzira',
    stock: 5,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/225/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '226',
    author: 'Odhise Grillo',
    title: 'Historia e Skënderbeut',
    stock: 10,
    genre: 'Histori',
    coverUrl: 'https://picsum.photos/seed/226/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '227',
    author: 'Astrid Lindgren',
    title: 'Pipi Çorapegjata',
    stock: 14,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/227/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '228',
    author: 'Mark Tuen',
    title: 'Aventurat e Hakëlberi Finit',
    stock: 1,
    genre: 'Aventurë',
    coverUrl: 'https://picsum.photos/seed/228/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '229',
    author: 'Johana Shpiri',
    title: 'Heidi',
    stock: 10,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/229/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '230',
    author: 'P.L Trevers',
    title: 'Meri Poppins',
    stock: 17,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/230/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '231',
    author: 'Luis Kerol',
    title: 'Liza në botën e çudirave',
    stock: 10,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/231/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '232',
    author: 'Jeronim Stilton',
    title: 'Dorëshkrimi misterioz I nostramiushit',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/232/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '233',
    author: 'Ron Roy',
    title: 'Misteri I hotelit të magjepsur',
    stock: 6,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/233/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '234',
    author: 'Ron Roy',
    title: 'Misteri I mujmjes së vjedhur',
    stock: 7,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/234/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '235',
    author: 'Ron Roy',
    title: 'Misteri I fantazmës në kështjellë',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/235/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '236',
    author: 'Ron Roy',
    title: 'Misteri I thesarit të mbytur',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/236/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '237',
    author: 'Ron Roy',
    title: 'Misteri I smeraldit të jaguarit',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/237/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '238',
    author: 'Ron Roy',
    title: 'Misteri I thesarit në ishull',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/238/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '239',
    author: 'Ron Roy',
    title: 'Misteri I pullës së vjedhur',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/239/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '240',
    author: 'Ron Roy',
    title: 'Misteri I gurit të çmuar',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/240/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '241',
    author: 'Ron Roy',
    title: 'Misteri në rërën thithëse',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/241/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '242',
    author: 'Ron Roy',
    title: 'Misteri I dinozaurit në qytet',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/242/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '243',
    author: 'Sulejman Omerbashi',
    title: 'Indriti dhe arusha',
    stock: 3,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/243/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '244',
    author: 'David Ualliams',
    title: 'Gjyshja Gango',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/244/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '245',
    author: 'Julie Sykes',
    title: 'Freja dhe Mjalti',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/245/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '246',
    author: 'Julie Sykes',
    title: 'Matilda dhe Perla',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/246/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '247',
    author: 'Julie Skyes',
    title: 'Skarleta dhe Flakërima',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/247/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '248',
    author: 'Julie Skyes',
    title: 'Lajla dhe Kërcimtari',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/248/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '249',
    author: 'Julie Skyes',
    title: 'Isabela dhe Reja',
    stock: 3,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/249/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '250',
    author: 'Julie Skyes',
    title: 'Livia dhe Flokëbora',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/250/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '251',
    author: 'Julie Skyes',
    title: 'Eva dhe Yllka',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/251/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '252',
    author: 'Julie Skyes',
    title: 'Roza dhe Kristali',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/252/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '253',
    author: 'Julie Skyes',
    title: 'Ariana dhe Pëshpëritësi',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/253/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '254',
    author: 'Julie Skyes',
    title: 'Sofia dhe Ylberi',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/254/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '255',
    author: 'Eleanor H. Porter',
    title: 'Poliana',
    stock: 6,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/255/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '256',
    author: 'Alba Janaqi',
    title: 'Bujaria',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/256/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '257',
    author: 'Suzy Klajn',
    title: 'Herri I tmerrshëm nga klasa II-B',
    stock: 5,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/257/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '258',
    author: 'Suzy Klajn',
    title: 'Herri I tmerrshëm zbërthen kodin',
    stock: 5,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/258/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '259',
    author: 'Suzy Klajn',
    title: 'Hherri I tmerrshëm dhe letrat e vdekura',
    stock: 5,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/259/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '260',
    author: 'Suzy Klajn',
    title: 'Herri I tmerrshëm për hallouin',
    stock: 3,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/260/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '261',
    author: 'Jenny',
    title: 'Ditari Rozë 2',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/261/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '262',
    author: 'Mihail Eminesku',
    title: 'Princi I bukur prej pikës së lotit',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/262/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '263',
    author: 'Xhani Rodari',
    title: 'Aventurat e Çipolinos',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/263/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '264',
    author: 'Bruce Covile',
    title: 'Mësuesi Alien',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/264/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '265',
    author: 'Xhani Rodari',
    title: 'Përralla në telefon',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/265/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '266',
    author: 'Xhani Rodari',
    title: 'Xhipi në televizor dhe ndodhi të tjera në orbitë',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/266/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '267',
    author: 'Xhani Rodari',
    title: 'Tregime të tjera',
    stock: 4,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/267/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '268',
    author: 'Xhani Rodari',
    title: 'Torta që ra nga qielli',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/268/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '269',
    author: 'Disney',
    title: 'Mbretëresha e akullit',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/269/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '270',
    author: 'Disney',
    title: 'Anna dhe Elsa - të gjithë përshëndesin mbretëreshën',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/270/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '271',
    author: 'Disney',
    title: 'Anna dhe Elsa - kujtime dhe magji',
    stock: 2,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/271/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '272',
    author: 'Disney',
    title: 'Anna dhe Elsa - një mikpritje e ngrohtë',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/272/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '273',
    author: 'Disney',
    title: 'Anna dhe Elsa - Olafi dhe arinjtë polar',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/273/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '274',
    author: 'Disney',
    title: 'Frozen II - Pylli magjik',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/274/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '275',
    author: 'James M. Barri',
    title: 'Piter Pan',
    stock: 22,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/275/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '276',
    author: 'Skënder Hasko',
    title: 'Arratisja e Tupe Xhelos',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/276/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '277',
    author: 'Frederik Reshpja',
    title: 'Legjendat e Arbërit',
    stock: 1,
    genre: 'Legjenda',
    coverUrl: 'https://picsum.photos/seed/277/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '278',
    author: 'Mimoza Tola',
    title: 'Ira bëri një emision',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/278/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '279',
    author: 'Alberto Moravia',
    title: 'Përralla',
    stock: 6,
    genre: 'Përralla',
    coverUrl: 'https://picsum.photos/seed/279/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '280',
    author: 'Xhani Rodari',
    title: 'Princesha gazmore',
    stock: 3,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/280/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '281',
    author: 'Viron Kona',
    title: 'Erlindi dhe papagalli I çuditshëm',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/281/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '282',
    author: 'Karlo Kolodi',
    title: 'Pinoku',
    stock: 1,
    genre: 'Fëmijë',
    coverUrl: 'https://picsum.photos/seed/282/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '283',
    author: 'Alexandre Dumas',
    title: 'Gostia e konteshës Berta',
    stock: 1,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/283/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '284',
    author: 'Fotaq Andrea',
    title: 'Mrekullinë njerëzore',
    stock: 6,
    genre: 'Letërsi',
    coverUrl: 'https://picsum.photos/seed/284/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  },
  {
    id: '285',
    author: 'Patrick Fischmann,Anna Lazowski',
    title: 'Përrallat e rojtarëve të mençur të detit',
    stock: 1,
    genre: 'Përralla',
    coverUrl: 'https://picsum.photos/seed/285/400/600',
    synopsis: 'Ky libër është pjesë e koleksionit tonë të ri.',
    published: '-',
    pages: 0,
    isbn: '-',
    rating: 4.5
  }
];
